// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtsix1UVPGrNmAtjdsbqpahijKDkCZJPo',
    appId: '1:99946340880:web:a99d70c3e775a37fcb6095',
    messagingSenderId: '99946340880',
    projectId: 'task-manager-28c54',
    authDomain: 'task-manager-28c54.firebaseapp.com',
    storageBucket: 'task-manager-28c54.firebasestorage.app',
    measurementId: 'G-FM68L5GJZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7CgacRpsSimIgGKmr-USelL_m8sBC-8',
    appId: '1:99946340880:android:f89ad387c029cb27cb6095',
    messagingSenderId: '99946340880',
    projectId: 'task-manager-28c54',
    storageBucket: 'task-manager-28c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLb1l9hHlpY9818mSybTToiaX0HV04w4',
    appId: '1:99946340880:ios:c7207f3bfaf27990cb6095',
    messagingSenderId: '99946340880',
    projectId: 'task-manager-28c54',
    storageBucket: 'task-manager-28c54.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRLb1l9hHlpY9818mSybTToiaX0HV04w4',
    appId: '1:99946340880:ios:c7207f3bfaf27990cb6095',
    messagingSenderId: '99946340880',
    projectId: 'task-manager-28c54',
    storageBucket: 'task-manager-28c54.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtsix1UVPGrNmAtjdsbqpahijKDkCZJPo',
    appId: '1:99946340880:web:b5cdfe13fafa4b1bcb6095',
    messagingSenderId: '99946340880',
    projectId: 'task-manager-28c54',
    authDomain: 'task-manager-28c54.firebaseapp.com',
    storageBucket: 'task-manager-28c54.firebasestorage.app',
    measurementId: 'G-PRYWBTPQTN',
  );
}
